issues:
    max-per-linter: 0
    max-same-issues: 0

linters:
    disable-all: true
    enable:
        - errcheck
        - gofmt
        - gosimple
        - ineffassign
        - misspell
        - nakedret
        - staticcheck
        - unconvert
        - unused
        - unparam
        - govet
        - gosec

run:
    timeout: 10m
    modules-download-mode: readonly